<?php
/**
* @file
* Generates demo content for Skeiðgnúp.
*/

function skeidgnup_demo_content_help($path, $arg) {
  switch ($path) {
    case "admin/help#skeidgnup_demo_content":
      return '<p>' . t("Býr til efni úr Lorem ipsum texta í allar efnistípur") . '</p>';
      break;
  }
}

function add_demo_content($type = NULL, $number = NULL, $file = NULL, $vocabulary = NULL) {
  
    $terms_news = array(
      
          array(
            'name' => t('Frétt'),
            'description' => t('Flokkur fyrir fréttatengt efni'),
          ),
          array(
            'name' => t('Fésið'),
            'description' => t('Færslur á fésbókina'),
          ),
          array(
            'name' => t('Síða'),
            'description' => t('Síður með upplýsingum eða fræðsluefni'),
          ),        
          array(
            'name' => t('Fundargerð'),
            'description' => t('Fundargerðir hjá nefndum sveitastjórnar.'),
          ),
          array(
            'name' => t('Laus störf'),
            'description' => t('Laust störf í hreppnum.'),
          ),
          array(
            'name' => t('Fréttabréf'),
            'description' => t('Setja efnið á minnislista fyrir næsta fréttabréf.'),
          ),
    );
    
    $terms_committee = array (
        array(
            'name' => t('Hreppsnefnd'),
        ),        
        array(
            'name' => t('Skólanefnd'),
        ),        
        array(
            'name' => t('Umhverfisnefnd'),
        ),        
        array(
            'name' => t('Almannavarnanefnd'),
        ),        
        array(
            'name' => t('Skipulags og byggingarnefnd'),
        ),        
        array(
            'name' => t('Brunavarnarnefnd'),
        ),        
        array(
            'name' => t('Hússtjórn Þjóðveldisbæjar'),
        ),        
        array(
            'name' => t('Landsþing SÍS'),
        ), 
        array(
            'name' => t('Ráðgjafanefnd um friðun Þjórsárvera'),
        ),
        array(
            'name' => t('Fræðslunefnd Flúðaskóla'),
        ),         
        array(
            'name' => t('Atvinnu, fjarskipta og samgöngunefnd'),
        ),         
        array(
            'name' => t('Menningar, æskulýðs, velferðar- og jafnréttisnefnd'),
        ),         
        array(
            'name' => t('Afréttarnefnd Gnúpverjaafréttar'),
        ),         
        array(
            'name' => t('Kjörstjórn'),
        ),         
        array(
            'name' => t('Félagsmálanefnd'),
        ),        
        array(
            'name' => t('Skoðunarmenn hreppsreikninga'),
        ),        
        array(
            'name' => t('Aðalfundur SASS'),
        ),        
        array(
            'name' => t('Aðalfundur Heilbrigðiseftirlits Suðurlands'),
        ),        
        array(
            'name' => t('Aðalfundur Skólaskrifstofu Suðurlands'),
        ),        
        array(
            'name' => t('Sorpstöð Suðurlands'),
        ),        
    );
    
    $number_of_news_terms = count($terms_news);
    $number_of_committee_terms = count($terms_committee);
    
  switch ($vocabulary) {
    case 'tax_category':
      if (!(taxonomy_term_load($number_of_news_terms))) {
        $vocabulary_obj = taxonomy_vocabulary_machine_name_load($vocabulary);    
        foreach ($terms_news as $term) {
          $term['vid'] = $vocabulary_obj->vid;
          $term = (object) $term;
          taxonomy_term_save($term);
        }    
      } // closing if statement
          
       $file_uri = path_to_theme() . '/' . $file;
       $body_text = drupal_ipsum_generate('icelandic', 15, DRUPAL_IPSUM_TYPE_SENTENCE, DRUPAL_IPSUM_START_ANY, TRUE);
       $file_obj = (object) array(
         'uid' => 1,
         'uri' => $file_uri,
         'filemime' => file_get_mimetype($file_uri),
         'status' => 1,
         'display' => 1,
       );
       
       $file_obj = file_copy($file_obj, 'public://', FILE_EXISTS_REPLACE);
       
         for ($i = 1; $i <= $number; $i++) {
             $node = new stdClass();
             $node->type = $type;
             node_object_prepare($node);
             $node->comment = 1;   
             $node->title    = drupal_ipsum_generate('icelandic', 4, DRUPAL_IPSUM_TYPE_WORD, DRUPAL_IPSUM_START_ANY, FALSE);
             $node->language = LANGUAGE_NONE;
             $node->field_post_body[$node->language][0]['value']   = $body_text;
             $node->field_post_body[$node->language][0]['summary'] = text_summary($body_text);
             $node->field_post_body[$node->language][0]['format']  = 'filtered_html';
             $node->field_post_category[$node->language][]['tid']  = rand(1, $number_of_news_terms);
             $node->field_post_image = array(LANGUAGE_NONE => array('0' => (array)$file_obj));

             
             if($node = node_submit($node)) { // Prepare node for saving
               node_save($node);
             }
             else
               return 'Eitthvað skrítið á seyði';
         }
        break;
    case 'committee':

      if (!(taxonomy_term_load($number_of_news_terms+$number_of_committee_terms))) {    
       $vocabulary_obj = taxonomy_vocabulary_machine_name_load($vocabulary);    
       foreach ($terms_committee as $term) {
         $term['vid'] = $vocabulary_obj->vid;       
         $term = (object) $term;
         taxonomy_term_save($term);
       }    
      } // closing if statement   
       $term_report = taxonomy_get_term_by_name('Fundargerð');
       $file_uri = path_to_theme() . '/' . $file;
       $body_text = drupal_ipsum_generate('icelandic', 15, DRUPAL_IPSUM_TYPE_SENTENCE, DRUPAL_IPSUM_START_ANY, TRUE);
       $file = (object) array(
         'uid' => 1,
         'uri' => $file_uri,
         'filemime' => file_get_mimetype($file_uri),
         'status' => 1,
         'display' => 1,
       );
       
       $file = file_copy($file, 'public://', FILE_EXISTS_REPLACE);
         for ($i = 1; $i <= $number; $i++) {
             $node = new stdClass();
             $node->type = $type;
             node_object_prepare($node);
             $node->comment = 1;   
             $node->title    = drupal_ipsum_generate('icelandic', 4, DRUPAL_IPSUM_TYPE_WORD, DRUPAL_IPSUM_START_ANY, FALSE);
             $node->language = LANGUAGE_NONE;
             $node->field_post_body[$node->language][0]['value']    = $body_text;
             $node->field_post_body[$node->language][0]['summary']  = text_summary($body_text);
             $node->field_post_body[$node->language][0]['format']   = 'filtered_html';
             $node->field_post_category[$node->language][]['tid']   = key($term_report);
             $node->field_post_committee[$node->language][]['tid']  = rand($number_of_news_terms, ($number_of_news_terms + $number_of_committee_terms));
             $node->field_post_attachment = array(LANGUAGE_NONE => array('0' => (array)$file));
             
             if($node = node_submit($node)) { // Prepare node for saving
               node_save($node);
             }
             else
               return 'Eitthvað skrítið á seyði';
         }

        break;
    }
}

function skeidgnup_demo_content_drupal_ipsum_vocabularies() {
  return array(
    'icelandic' => array( // Your vocabulary's machine_name.
      'title' => 'Icelandic words',
      'words' => array(
        'minnum',
        'á',
        'strætóferðirnar',
        'óviðráðanlegum',
        'orsökum',
        'sveitarstjórnarfundi',
        'desember',
        'fundurinn',
        'deiliskipulags',
        'í',
        'og',
        'með',
        'saman',
        'örlítið',
        'ljósleiðarakerfis',
        'spildu',
        'landi',
        'ESA', 
        'að', 
        'þeirri', 
        'niðurstöðu', 
        'að', 
        'það',
        'væri',
        'til',
        'þess',
        'fallið',
        'auka',
        'samkeppnishæfni',
        'þessa', 
      ),
    ),
  );
}

function skeidgnup_demo_content_menu() {
  $items['skeidgnup-demo-content'] = array(
    'title' => 'Demo content',
    'description' => t('Create loads of content!'),
    'page callback' => 'skeidgnup_demo_content_makeit',
    'access callback' => TRUE,
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'navigation',
  );
  return $items;
}

function skeidgnup_demo_content_makeit() {
  //$type, $number, $file, $vocabulary_machine_name
  add_demo_content('post', 50, 'thjorsardalur.jpg', 'tax_category');
  add_demo_content('post', 50, 'pdf_demo.pdf', 'committee');  
  return 'Allt gekk eins og í sögu.. bæ :-)';
}