<?php
/**
* @file
* Generates demo content for Skeiðgnúp.
*/

function skeidgnup_demo_content_help($path, $arg) {
  switch ($path) {
    case "admin/help#skeidgnup_demo_content":
      return '<p>' . t("Býr til efni úr Lorem ipsum texta í allar efnistípur") . '</p>';
      break;
  }
}

function add_demo_content($type = NULL, $number = NULL, $file = NULL, $taxonomy = NULL) {
  
    $terms_news = array(
      
        $t1 = array(
            'name' => t('Frétt'),
            'description' => t('Flokkur fyrir fréttatengt efni'),
            'vid' => 1,
        ),
        $t2 = array(
            'name' => t('Fésið'),
            'description' => t('Færslur á fésbókina'),
            'vid' => 1,
        ),
        $t3 = array(
            'name' => t('Síða'),
            'description' => t('Síður með upplýsingum eða fræðsluefni'),
            'vid' => 1,
        ),        
        $t4 = array(
            'name' => t('Fundargerð'),
            'description' => t('Fundargerðir hjá nefndum sveitastjórnar.'),
            'vid' => 1,
        ),
        $t5 = array(
            'name' => t('Laus störf'),
            'description' => t('Laust störf í hreppnum.'),
            'vid' => 1,
        ),
        $t6 = array(
            'name' => t('Fréttabréf'),
            'description' => t('Setja efnið á minnislista fyrir næsta fréttabréf.'),
            'vid' => 1,
        ),
    );
    
    $terms_committee = array (
        $t7 = array(
            'name' => t('Hreppsnefnd'),
            'vid' => 2,
        ),        
        $t8 = array(
            'name' => t('Skólanefnd'),
            'vid' => 2,
        ),        
        $t9 = array(
            'name' => t('Umhverfisnefnd'),
            'vid' => 2,
        ),        
        $t10 = array(
            'name' => t('Almannavarnanefnd'),
            'vid' => 2,
        ),        
        $t11 = array(
            'name' => t('Skipulags og byggingarnefnd'),
            'vid' => 2,
        ),        
        $t12 = array(
            'name' => t('Brunavarnarnefnd'),
            'vid' => 2,
        ),        
        $t13 = array(
            'name' => t('Hússtjórn Þjóðveldisbæjar'),
            'vid' => 2,
        ),        
        $t14 = array(
            'name' => t('Landsþing SÍS'),
            'vid' => 2,
        ), 
        $t15 = array(
            'name' => t('Ráðgjafanefnd um friðun Þjórsárvera'),
            'vid' => 2,
        ),
        $t16 = array(
            'name' => t('Fræðslunefnd Flúðaskóla'),
            'vid' => 2,
        ),         
        $t17 = array(
            'name' => t('Atvinnu, fjarskipta og samgöngunefnd'),
            'vid' => 2,
        ),         
        $t18 = array(
            'name' => t('Menningar, æskulýðs, velferðar- og jafnréttisnefnd'),
            'vid' => 2,
        ),         
        $t19 = array(
            'name' => t('Afréttarnefnd Gnúpverjaafréttar'),
            'vid' => 2,
        ),         
        $t20 = array(
            'name' => t('Kjörstjórn'),
            'vid' => 2,
        ),         
        $t21 = array(
            'name' => t('Félagsmálanefnd'),
            'vid' => 2,
        ),        
        $t22 = array(
            'name' => t('Skoðunarmenn hreppsreikninga'),
            'vid' => 2,
        ),        
        $t23 = array(
            'name' => t('Aðalfundur SASS'),
            'vid' => 2,
        ),        
        $t24 = array(
            'name' => t('Aðalfundur Heilbrigðiseftirlits Suðurlands'),
            'vid' => 2,
        ),        
        $t25 = array(
            'name' => t('Aðalfundur Skólaskrifstofu Suðurlands'),
            'vid' => 2,
        ),        
        $t26 = array(
            'name' => t('Sorpstöð Suðurlands'),
            'vid' => 2,
        ),        
    );
    
    $number_of_news_terms = count($terms_news);
    $number_of_committee_terms = count($terms_committee);    
    if (taxonomy_term_load(1) == FALSE) {
      foreach ($terms_news as $term) {
        $term = (object) $term;
        taxonomy_term_save($term);
      }    
      foreach ($terms_committee as $term) {
        $term = (object) $term;
        taxonomy_term_save($term);
      }    

  }
    
  switch ($taxonomy) {
    case 'news':
       $file_uri = path_to_theme() . '/' . $file;
       $body_text = drupal_ipsum_generate('icelandic', 15, DRUPAL_IPSUM_TYPE_SENTENCE, DRUPAL_IPSUM_START_ANY, TRUE);
       $file_obj = (object) array(
         'uid' => 1,
         'uri' => $file_uri,
         'filemime' => file_get_mimetype($file_uri),
         'status' => 1,
         'display' => 1,
       );
       
       $file_obj = file_copy($file_obj, 'public://', FILE_EXISTS_REPLACE);
       
         for ($i = 1; $i <= $number; $i++) {
             $node = new stdClass();
             $node->type = $type;
             node_object_prepare($node);
             $node->comment = 1;   
             $node->title    = drupal_ipsum_generate('icelandic', 4, DRUPAL_IPSUM_TYPE_WORD, DRUPAL_IPSUM_START_ANY, FALSE);
             $node->language = LANGUAGE_NONE;
             $node->field_post_body[$node->language][0]['value']   = $body_text;
             $node->field_post_body[$node->language][0]['summary'] = text_summary($body_text);
             $node->field_post_body[$node->language][0]['format']  = 'filtered_html';
             $node->field_post_category[$node->language][]['tid'] = rand(1, $number_of_news_terms);
             $node->field_post_image = array(LANGUAGE_NONE => array('0' => (array)$file_obj));

             
             if($node = node_submit($node)) { // Prepare node for saving
               node_save($node);
             }
             else
               return 'Eitthvað skrítið á seyði';
         }
        break;
    case 'meeting':
       $file_uri = path_to_theme() . '/' . $file;
       $body_text = drupal_ipsum_generate('icelandic', 15, DRUPAL_IPSUM_TYPE_SENTENCE, DRUPAL_IPSUM_START_ANY, TRUE);
       $file = (object) array(
         'uid' => 1,
         'uri' => $file_uri,
         'filemime' => file_get_mimetype($file_uri),
         'status' => 1,
         'display' => 1,
       );
       
       $file = file_copy($file, 'public://', FILE_EXISTS_REPLACE);
       
         for ($i = 1; $i <= $number; $i++) {
             $node = new stdClass();
             $node->type = $type;
             node_object_prepare($node);
             $node->comment = 1;   
             $node->title    = drupal_ipsum_generate('icelandic', 4, DRUPAL_IPSUM_TYPE_WORD, DRUPAL_IPSUM_START_ANY, FALSE);
             $node->language = LANGUAGE_NONE;
             $node->field_post_body[$node->language][0]['value']   = $body_text;
             $node->field_post_body[$node->language][0]['summary'] = text_summary($body_text);
             $node->field_post_body[$node->language][0]['format']  = 'filtered_html';
             $node->field_post_category[$node->language][]['tid'] = rand(7, $number_of_commiterms);
             $node->field_post_category[$node->language][]['tid'] = rand(7, $number_of_commiterms);
             $node->field_post_attachment = array(LANGUAGE_NONE => array('0' => (array)$file));

             
             if($node = node_submit($node)) { // Prepare node for saving
               node_save($node);
             }
             else
               return 'Eitthvað skrítið á seyði';
         }
        break;
    }
}

function skeidgnup_demo_content_drupal_ipsum_vocabularies() {
  return array(
    'icelandic' => array( // Your vocabulary's machine_name.
      'title' => 'Icelandic words',
      'words' => array(
        'minnum',
        'á',
        'strætóferðirnar',
        'óviðráðanlegum',
        'orsökum',
        'sveitarstjórnarfundi',
        'desember',
        'fundurinn',
        'deiliskipulags',
        'í',
        'og',
        'með',
        'saman',
        'örlítið',
        'ljósleiðarakerfis',
        'spildu',
        'landi',
        'ESA', 
        'að', 
        'þeirri', 
        'niðurstöðu', 
        'að', 
        'það',
        'væri',
        'til',
        'þess',
        'fallið',
        'auka',
        'samkeppnishæfni',
        'þessa', 
      ),
    ),
  );
}

function skeidgnup_demo_content_menu() {
  $items['skeidgnup-demo-content'] = array(
    'title' => 'Demo content',
    'description' => t('Create loads of content!'),
    'page callback' => 'skeidgnup_demo_content_makeit',
    'access callback' => TRUE,
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'navigation',
  );
  return $items;
}

function skeidgnup_demo_content_makeit() {
  //$type, $number, $file, $taxonomy
  add_demo_content('post', 50, 'thjorsardalur.jpg', 'news');
  add_demo_content('post', 50, 'pdf_demo.pdf', 'committee');  
  return 'Allt gekk eins og í sögu.. bæ :-)';
}